// ------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本: 17.0.0.0
//  
//     对此文件的更改可能导致不正确的行为，如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Z.Fantasy.GenerateCode.Template.SunBlog.Application
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\A_Code\fantasy-ke.github.io\Z.Fantasy.GenerateCode\Z.Fantasy.GenerateCode\Template\SunBlog\Application\AchieveAppService.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class AchieveAppService : AchieveAppServiceBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("using Microsoft.AspNetCore.Mvc;\r\nusing Microsoft.EntityFrameworkCore;\r\nusing Z.Fa" +
                    "ntasy.Core.DomainServiceRegister;\r\nusing Z.SunBlog.Core.SharedDto;\r\nusing ");
            
            #line 9 "E:\A_Code\fantasy-ke.github.io\Z.Fantasy.GenerateCode\Z.Fantasy.GenerateCode\Template\SunBlog\Application\AchieveAppService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(data.CoreNamespace));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 9 "E:\A_Code\fantasy-ke.github.io\Z.Fantasy.GenerateCode\Z.Fantasy.GenerateCode\Template\SunBlog\Application\AchieveAppService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(data.ModelName));
            
            #line default
            #line hidden
            this.Write("Module.DomainManager;\r\nusing ");
            
            #line 10 "E:\A_Code\fantasy-ke.github.io\Z.Fantasy.GenerateCode\Z.Fantasy.GenerateCode\Template\SunBlog\Application\AchieveAppService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(data.AppNamespace));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 10 "E:\A_Code\fantasy-ke.github.io\Z.Fantasy.GenerateCode\Z.Fantasy.GenerateCode\Template\SunBlog\Application\AchieveAppService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(data.ModelName));
            
            #line default
            #line hidden
            this.Write("Module.Dto;\r\nusing ");
            
            #line 11 "E:\A_Code\fantasy-ke.github.io\Z.Fantasy.GenerateCode\Z.Fantasy.GenerateCode\Template\SunBlog\Application\AchieveAppService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(data.CoreNamespace));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 11 "E:\A_Code\fantasy-ke.github.io\Z.Fantasy.GenerateCode\Z.Fantasy.GenerateCode\Template\SunBlog\Application\AchieveAppService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(data.ModelName));
            
            #line default
            #line hidden
            this.Write("Module;\r\n\r\nnamespace ");
            
            #line 13 "E:\A_Code\fantasy-ke.github.io\Z.Fantasy.GenerateCode\Z.Fantasy.GenerateCode\Template\SunBlog\Application\AchieveAppService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(data.AppNamespace));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 13 "E:\A_Code\fantasy-ke.github.io\Z.Fantasy.GenerateCode\Z.Fantasy.GenerateCode\Template\SunBlog\Application\AchieveAppService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(data.ModelName));
            
            #line default
            #line hidden
            this.Write("Module;\r\n\r\n/// <summary>\r\n/// ");
            
            #line 16 "E:\A_Code\fantasy-ke.github.io\Z.Fantasy.GenerateCode\Z.Fantasy.GenerateCode\Template\SunBlog\Application\AchieveAppService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(data.TableNameDes));
            
            #line default
            #line hidden
            this.Write("应用服务\r\n/// </summary>\r\npublic class ");
            
            #line 18 "E:\A_Code\fantasy-ke.github.io\Z.Fantasy.GenerateCode\Z.Fantasy.GenerateCode\Template\SunBlog\Application\AchieveAppService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(data.ModelName));
            
            #line default
            #line hidden
            this.Write("AppService : ApplicationService, I");
            
            #line 18 "E:\A_Code\fantasy-ke.github.io\Z.Fantasy.GenerateCode\Z.Fantasy.GenerateCode\Template\SunBlog\Application\AchieveAppService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(data.ModelName));
            
            #line default
            #line hidden
            this.Write("AppService\r\n{\r\n    private readonly I");
            
            #line 20 "E:\A_Code\fantasy-ke.github.io\Z.Fantasy.GenerateCode\Z.Fantasy.GenerateCode\Template\SunBlog\Application\AchieveAppService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(data.ModelName));
            
            #line default
            #line hidden
            this.Write("Manager _");
            
            #line 20 "E:\A_Code\fantasy-ke.github.io\Z.Fantasy.GenerateCode\Z.Fantasy.GenerateCode\Template\SunBlog\Application\AchieveAppService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(data.CamelModelName));
            
            #line default
            #line hidden
            this.Write("Manager;\r\n    public ");
            
            #line 21 "E:\A_Code\fantasy-ke.github.io\Z.Fantasy.GenerateCode\Z.Fantasy.GenerateCode\Template\SunBlog\Application\AchieveAppService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(data.ModelName));
            
            #line default
            #line hidden
            this.Write("AppService(\r\n        IServiceProvider serviceProvider, I");
            
            #line 22 "E:\A_Code\fantasy-ke.github.io\Z.Fantasy.GenerateCode\Z.Fantasy.GenerateCode\Template\SunBlog\Application\AchieveAppService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(data.ModelName));
            
            #line default
            #line hidden
            this.Write("Manager ");
            
            #line 22 "E:\A_Code\fantasy-ke.github.io\Z.Fantasy.GenerateCode\Z.Fantasy.GenerateCode\Template\SunBlog\Application\AchieveAppService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(data.CamelModelName));
            
            #line default
            #line hidden
            this.Write("Manager) : base(serviceProvider)\r\n    {\r\n        _");
            
            #line 24 "E:\A_Code\fantasy-ke.github.io\Z.Fantasy.GenerateCode\Z.Fantasy.GenerateCode\Template\SunBlog\Application\AchieveAppService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(data.CamelModelName));
            
            #line default
            #line hidden
            this.Write("Manager = ");
            
            #line 24 "E:\A_Code\fantasy-ke.github.io\Z.Fantasy.GenerateCode\Z.Fantasy.GenerateCode\Template\SunBlog\Application\AchieveAppService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(data.CamelModelName));
            
            #line default
            #line hidden
            this.Write("Manager;\r\n    }\r\n\r\n    /// <summary>\r\n    /// 添加修改\r\n    /// </summary>\r\n    /// <" +
                    "param name=\"dto\"></param>\r\n    /// <returns></returns>\r\n    public async Task Cr" +
                    "eateOrUpdate(CreateOrUpdate");
            
            #line 32 "E:\A_Code\fantasy-ke.github.io\Z.Fantasy.GenerateCode\Z.Fantasy.GenerateCode\Template\SunBlog\Application\AchieveAppService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(data.ModelName));
            
            #line default
            #line hidden
            this.Write("Input dto)\r\n    {\r\n        var isUpdated = ");
            
            #line 34 "E:\A_Code\fantasy-ke.github.io\Z.Fantasy.GenerateCode\Z.Fantasy.GenerateCode\Template\SunBlog\Application\AchieveAppService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(data.IdType switch
                            {
                                "Guid" => "dto.Id != null &&dto.Id != Guid.Empty;",
                                "int" => "dto.Id > 0;",
                                _ => "false"
                                }));
            
            #line default
            #line hidden
            this.Write(@"

        if (isUpdated)
        {
            await Update(dto);
            return;
        }

        await Create(dto);
    }

    /// <summary>
    /// 删除
    /// </summary>
    /// <param name=""dto""></param>
    /// <returns></returns>
    [HttpDelete]
    public async Task DeleteAsync(KeyDto dto)
    {
        await _");
            
            #line 58 "E:\A_Code\fantasy-ke.github.io\Z.Fantasy.GenerateCode\Z.Fantasy.GenerateCode\Template\SunBlog\Application\AchieveAppService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(data.CamelModelName));
            
            #line default
            #line hidden
            this.Write("Manager.DeleteAsync(");
            
            #line 58 "E:\A_Code\fantasy-ke.github.io\Z.Fantasy.GenerateCode\Z.Fantasy.GenerateCode\Template\SunBlog\Application\AchieveAppService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(data.IdType == "int" ? "dto.NumberId" : "dto.Id"));
            
            #line default
            #line hidden
            this.Write(");\r\n    }\r\n\r\n    /// <summary>\r\n    /// 添加");
            
            #line 63 "E:\A_Code\fantasy-ke.github.io\Z.Fantasy.GenerateCode\Z.Fantasy.GenerateCode\Template\SunBlog\Application\AchieveAppService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(data.TableNameDes));
            
            #line default
            #line hidden
            this.Write("\r\n    /// </summary>\r\n    /// <param name=\"dto\"></param>\r\n    /// <returns></retu" +
                    "rns>\r\n    private async Task Create(CreateOrUpdate");
            
            #line 67 "E:\A_Code\fantasy-ke.github.io\Z.Fantasy.GenerateCode\Z.Fantasy.GenerateCode\Template\SunBlog\Application\AchieveAppService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(data.ModelName));
            
            #line default
            #line hidden
            this.Write("Input dto)\r\n    {\r\n        var ");
            
            #line 69 "E:\A_Code\fantasy-ke.github.io\Z.Fantasy.GenerateCode\Z.Fantasy.GenerateCode\Template\SunBlog\Application\AchieveAppService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(data.CamelModelName));
            
            #line default
            #line hidden
            this.Write(" = ObjectMapper.Map<");
            
            #line 69 "E:\A_Code\fantasy-ke.github.io\Z.Fantasy.GenerateCode\Z.Fantasy.GenerateCode\Template\SunBlog\Application\AchieveAppService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(data.ModelName));
            
            #line default
            #line hidden
            this.Write(">(dto);\r\n        ");
            
            #line 70 "E:\A_Code\fantasy-ke.github.io\Z.Fantasy.GenerateCode\Z.Fantasy.GenerateCode\Template\SunBlog\Application\AchieveAppService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(data.IdType switch
           {
               "Guid" => $"{data.CamelModelName}.Id = Guid.NewGuid();",
               _ => ""
           }));
            
            #line default
            #line hidden
            this.Write("\r\n        await _");
            
            #line 75 "E:\A_Code\fantasy-ke.github.io\Z.Fantasy.GenerateCode\Z.Fantasy.GenerateCode\Template\SunBlog\Application\AchieveAppService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(data.CamelModelName));
            
            #line default
            #line hidden
            this.Write("Manager.CreateAsync(");
            
            #line 75 "E:\A_Code\fantasy-ke.github.io\Z.Fantasy.GenerateCode\Z.Fantasy.GenerateCode\Template\SunBlog\Application\AchieveAppService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(data.CamelModelName));
            
            #line default
            #line hidden
            this.Write(");\r\n    }\r\n\r\n    /// <summary>\r\n    /// 更新");
            
            #line 79 "E:\A_Code\fantasy-ke.github.io\Z.Fantasy.GenerateCode\Z.Fantasy.GenerateCode\Template\SunBlog\Application\AchieveAppService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(data.TableNameDes));
            
            #line default
            #line hidden
            this.Write("\r\n    /// </summary>\r\n    /// <returns></returns>\r\n    private async Task Update(" +
                    "CreateOrUpdate");
            
            #line 82 "E:\A_Code\fantasy-ke.github.io\Z.Fantasy.GenerateCode\Z.Fantasy.GenerateCode\Template\SunBlog\Application\AchieveAppService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(data.ModelName));
            
            #line default
            #line hidden
            this.Write("Input dto)\r\n    {\r\n        var ");
            
            #line 84 "E:\A_Code\fantasy-ke.github.io\Z.Fantasy.GenerateCode\Z.Fantasy.GenerateCode\Template\SunBlog\Application\AchieveAppService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(data.CamelModelName));
            
            #line default
            #line hidden
            this.Write(" = await _");
            
            #line 84 "E:\A_Code\fantasy-ke.github.io\Z.Fantasy.GenerateCode\Z.Fantasy.GenerateCode\Template\SunBlog\Application\AchieveAppService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(data.CamelModelName));
            
            #line default
            #line hidden
            this.Write("Manager.FindByIdAsync(");
            
            #line 84 "E:\A_Code\fantasy-ke.github.io\Z.Fantasy.GenerateCode\Z.Fantasy.GenerateCode\Template\SunBlog\Application\AchieveAppService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(data.IdType switch
           {
               "Guid" => $"dto.Id!.Value",
               _ => "dto.Id"
           }));
            
            #line default
            #line hidden
            this.Write(");\r\n\r\n        ObjectMapper.Map(dto, ");
            
            #line 90 "E:\A_Code\fantasy-ke.github.io\Z.Fantasy.GenerateCode\Z.Fantasy.GenerateCode\Template\SunBlog\Application\AchieveAppService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(data.CamelModelName));
            
            #line default
            #line hidden
            this.Write(");\r\n\r\n        await _");
            
            #line 92 "E:\A_Code\fantasy-ke.github.io\Z.Fantasy.GenerateCode\Z.Fantasy.GenerateCode\Template\SunBlog\Application\AchieveAppService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(data.CamelModelName));
            
            #line default
            #line hidden
            this.Write("Manager.UpdateAsync(");
            
            #line 92 "E:\A_Code\fantasy-ke.github.io\Z.Fantasy.GenerateCode\Z.Fantasy.GenerateCode\Template\SunBlog\Application\AchieveAppService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(data.CamelModelName));
            
            #line default
            #line hidden
            this.Write("!);\r\n    }\r\n\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public class AchieveAppServiceBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        public System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
